#!/bin/sh
set -euo pipefail

[ $# -lt 1 ] \
	&& echo "Usage: $(basename $0) <name>" \
	&& exit 1
[ "${1#*/}" != "$1" ] \
	&& echo "Usage: $(basename $0) <name>, / not permitted in <name>" \
	&& exit 1
[ "${1#.}" != "$1" ] \
	&& echo "Usage: $(basename $0) <name>, <name> may not start with ." \
	&& exit 1
[ -e "$1.git" ] \
	&& echo "$1 already exists" \
	&& exit 1
printf "default branch [main]: "
if ! read -r branch; then
	exit 1
fi
if [ -z "$branch" ]; then
	branch=main
fi
if ! git check-ref-format --branch "$branch" >/dev/null; then
	exit 1
fi
git init --bare -b "$branch" "$1.git"
